<?php

/**
 * @file Coupon.php
 * @author 贾晨辉(jiachenhui01@baidu.com)
 * @date 2012/12/12 19:10:09
 * @brief 团购券常量
 *
 **/

class SF_Const_Coupon
{


    const SMS_BLOCK_VALID_TIME = '有效期至：YEAR年MONTH月DAY日。';
    const SMS_BLOCK_SHOPPHONE = Tp_Adapter::SMS_SHOP_PHONE_TEMPLATE;
    const SMS_BLOCK_SHOPADDR = Tp_Adapter::SMS_SHOP_ADDRESS_TEMPLATE;
    const SMS_BLOCK_INSCRIBLOR = Tp_Adapter::SMS_BAIDU_PLATFORM_INSCRIBOR;
    const SMS_BLOCK_THIRD_SITE_INSCRIBLOR = Tp_Adapter::SMS_THIRD_SITE_INSCRIBOR;
    //物流单下单短信
    const COUPON_DELIVER_SMS_SEND_CODES = '您已购买COUPON_SMS_TITLE，预计DELIVER_TIME发货，商家联系电话COUPON_SMS_SHOP_PHONE。';
    const COUPON_DELIVER_SMS_EXCEPTION = '您团购的COUPON_SMS_TITLE项目出现异常，请联系客服电话4000-998-998。';
    const COUPON_DELIVER_SMS_WITHOUT_PHONE = '您团购的COUPON_SMS_TITLE项目，商家信息不全，请联系客服电话4000-998-998。';
    //物流单发货短信
    const COUPON_DELIVERED_SMS = '您团购的COUPON_SMS_TITLE已发货，运单号DELIVER_NO，DELIVER_COMPANY,预计DELIVERY_DATES天后到货，商家联系电话COUPON_SMS_SHOP_PHONE。';
    const COUPON_DELIVERED_SMS_EXCEPTION = '您团购的COUPON_SMS_TITLE项目发货的商家信息不全，请联系客服电话4000-998-998。';
    
    //电影订座码商品购买短信模板
    const COUPON_MAP_MOVIE_ITEM_SMS_URL = '您成功购买【SITE_NAME】COUPON_SMS_TITLE COUNT 张。有效期至MONTH月DAY日，兑票请戳 URL。此链接为唯一兑换入口，请妥善保存并及时兑换。祝您观影愉快！';
    const COUPON_MAP_MOVIE_ITEM_SMS_NOURL = '您成功购买【SITE_NAME】COUPON_SMS_TITLE COUNT 张, 券号：COUPON_SMS_CODES。有效期至MONTH月DAY日。祝您观影愉快！';
    
    
    const SMS_BLOCK_INFO_TAG = 'SMS_BLOCK_INFO';
    const SMS_BLOCK_COUPON_TAG = 'SMS_BLOCK_COUPON';
    const SMS_BLOCK_WEB_TAG ='SMS_BLOCK_WEB';
    const SMS_BLOCK_HINT_NOPASS_TAG ='SMS_BLOCK_HINT_NOPASS';
    const SMS_BLOCK_VALID_TIME_TAG ='SMS_BLOCK_VALID_TIME';
    const SMS_BLOCK_SHOPPHONE_TAG ='SMS_BLOCK_SHOPPHONE';
    const SMS_BLOCK_INSCRIBLOR_TAG ='SMS_BLOCK_INSCRIBLOR';
    const SMS_BLOCK_THIRD_SITE_INSCRIBLOR_TAG ='SMS_BLOCK_THIRD_SITE_INSCRIBLOR';

    public static $blockMapping = array(
        self::SMS_BLOCK_INFO_TAG => self::SMS_BLOCK_INFO,
        self::SMS_BLOCK_COUPON_TAG =>  self::SMS_BLOCK_COUPON,
        self::SMS_BLOCK_WEB_TAG=> self::SMS_BLOCK_WEB,
        self::SMS_BLOCK_HINT_NOPASS_TAG=> self::SMS_BLOCK_HINT_NOPASS,
        self::SMS_BLOCK_VALID_TIME_TAG=> self::SMS_BLOCK_VALID_TIME,
        self::SMS_BLOCK_SHOPPHONE_TAG=> self::SMS_BLOCK_SHOPPHONE,
        self::SMS_BLOCK_INSCRIBLOR_TAG=> self::SMS_BLOCK_INSCRIBLOR,
        self::SMS_BLOCK_THIRD_SITE_INSCRIBLOR_TAG=> self::SMS_BLOCK_THIRD_SITE_INSCRIBLOR,
    );

    const SMS_BLOCK_DELIMITER = '|';

    const SMS_BLOCK_INFO = '您已购买【SITE_NAME】COUPON_SMS_TITLE，单价为PRICE元，共COUNT份';
    const SMS_BLOCK_COUPON = '券号：COUPON_SMS_CODES。';
    const SMS_BLOCK_WEB = '可直接到网站发送团购券号。';
    const SMS_BLOCK_HINT_NOPASS = '使用时直接输入券号即可消费，无需密码。';

    const COUPON_SMS_SEND_CODES = 'SMS_BLOCK_INFO|,|SMS_BLOCK_COUPON|SMS_BLOCK_VALID_TIME|SMS_BLOCK_SHOPPHONE|SMS_BLOCK_INSCRIBLOR';
    const COUPON_SMS_SEND_NOTICE = 'SMS_BLOCK_INFO|,|SMS_BLOCK_WEB|SMS_BLOCK_SHOPPHONE|SMS_BLOCK_INSCRIBLOR';
    const COUPON_SMS_SEND_CODES_WITHOUT_PHONE = 'SMS_BLOCK_INFO|,|SMS_BLOCK_COUPON|SMS_BLOCK_VALID_TIME|SMS_BLOCK_INSCRIBLOR';
    const COUPON_SMS_SEND_NOTICE_WITHOUT_PHONE = ' SMS_BLOCK_INFO|,|SMS_BLOCK_WEB|SMS_BLOCK_INSCRIBLOR';

    const COUPON_TP_SMS_SEND_CODES = 'SMS_BLOCK_INFO|,|SMS_BLOCK_COUPON|SMS_BLOCK_HINT_NOPASS|SMS_BLOCK_VALID_TIME|SMS_BLOCK_SHOPPHONE|SMS_BLOCK_THIRD_SITE_INSCRIBLOR|SMS_BLOCK_INSCRIBLOR';
    const COUPON_TP_SMS_SEND_NOTICE = 'SMS_BLOCK_INFO|,|SMS_BLOCK_WEB|SMS_BLOCK_HINT_NOPASS|SMS_BLOCK_SHOPPHONE|SMS_BLOCK_THIRD_SITE_INSCRIBLOR|SMS_BLOCK_INSCRIBLOR';
    const COUPON_TP_SMS_SEND_CODES_WITHOUT_PHONE = 'SMS_BLOCK_INFO|,|SMS_BLOCK_COUPON|SMS_BLOCK_HINT_NOPASS|SMS_BLOCK_VALID_TIME|SMS_BLOCK_THIRD_SITE_INSCRIBLOR|SMS_BLOCK_INSCRIBLOR';
    const COUPON_TP_SMS_SEND_NOTICE_WITHOUT_PHONE = 'SMS_BLOCK_INFO|,|SMS_BLOCK_WEB|SMS_BLOCK_HINT_NOPASS|SMS_BLOCK_THIRD_SITE_INSCRIBLOR|SMS_BLOCK_INSCRIBLOR';


    const COUPON_TP_SMS_SEND_CODES_V1 = 'SMS_BLOCK_INFO|,|SMS_BLOCK_COUPON|SMS_BLOCK_VALID_TIME|SMS_BLOCK_SHOPPHONE|SMS_BLOCK_THIRD_SITE_INSCRIBLOR|SMS_BLOCK_INSCRIBLOR';
    const COUPON_TP_SMS_SEND_NOTICE_V1 = 'SMS_BLOCK_INFO|,|SMS_BLOCK_WEB|SMS_BLOCK_HINT_NOPASS|SMS_BLOCK_SHOPPHONE|SMS_BLOCK_THIRD_SITE_INSCRIBLOR|SMS_BLOCK_INSCRIBLOR';
    const COUPON_TP_SMS_SEND_CODES_WITHOUT_PHONE_V1 = 'SMS_BLOCK_INFO|,|SMS_BLOCK_COUPON|SMS_BLOCK_VALID_TIME|SMS_BLOCK_THIRD_SITE_INSCRIBLOR|SMS_BLOCK_INSCRIBLOR';
    const COUPON_TP_SMS_SEND_NOTICE_WITHOUT_PHONE_V1 = 'SMS_BLOCK_INFO|,|SMS_BLOCK_WEB|SMS_BLOCK_HINT_NOPASS|SMS_BLOCK_THIRD_SITE_INSCRIBLOR|SMS_BLOCK_INSCRIBLOR';

    const COUPON_TP_SMS_SEND_CODES_V2 = 'SMS_BLOCK_INFO|,|SMS_BLOCK_COUPON|SMS_BLOCK_VALID_TIME|SMS_BLOCK_SHOPPHONE|SMS_BLOCK_THIRD_SITE_INSCRIBLOR|SMS_BLOCK_INSCRIBLOR';
    const COUPON_TP_SMS_SEND_NOTICE_V2 = 'SMS_BLOCK_INFO|,|SMS_BLOCK_WEB|SMS_BLOCK_SHOPPHONE|SMS_BLOCK_THIRD_SITE_INSCRIBLOR|SMS_BLOCK_INSCRIBLOR';
    const COUPON_TP_SMS_SEND_CODES_WITHOUT_PHONE_V2 = 'SMS_BLOCK_INFO|,|SMS_BLOCK_COUPON|SMS_BLOCK_VALID_TIME|SMS_BLOCK_THIRD_SITE_INSCRIBLOR|SMS_BLOCK_INSCRIBLOR';
    const COUPON_TP_SMS_SEND_NOTICE_WITHOUT_PHONE_V2 = 'SMS_BLOCK_INFO|,|SMS_BLOCK_WEB|SMS_BLOCK_THIRD_SITE_INSCRIBLOR|SMS_BLOCK_INSCRIBLOR';

    const COUPON_SMS_EXPIRING_NOTIFCATION = '您购买的【SITE_NAME】COUPON_SMS_TITLE团购券即将于YEAR年MONTH月DAY日到期，请尽快消费。';
    const COUPON_SMS_REFUND_SUCCESS = '您申请的【SITE_NAME】COUPON_SMS_TITLE团购券退款，已经为您办理，退款金额会在7-15个工作日退还到您的支付账户。';
    const COUPON_SMS_REFUND_ERROR = '您申请的【SITE_NAME】COUPON_SMS_TITLE团购券退款，退款失败，请联系客服，客服电话4000-998-998。';
    const COUPON_SMS_VERIFY_NOTIFICATION = '您所购买的【SITE_NAME】COUPON_SMS_TITLE，团购券号COUPON_SMS_CODES已成功消费。';

    const COUPON_SMS_ERROR = '您团购的COUPON_SMS_TITLE项目出现异常，请联系客服电话4000-998-998。';

    const COUPON_SMS_SELLOUT = '您购买的【 SITE_NAME】COUPON_SMS_TITLE卖完了，已经为您办理退款，退款金额会在7-15个工作日退还到您的支付账户，请关注余额变化，客服咨询电话4000-998-998。';
    const COUPON_SMS_EXCEPTION = '您的【 SITE_NAME】COUPON_SMS_TITLE购买失败了，已经为您办理退款，退款金额会在7-15个工作日退还到您的支付账户，请关注余额变化，客服咨询电话4000-998-998。';

    const COUPON_ACTSCTRL_COMMAND_NO = 20001;

    const COUPON_ADD_COUPON_MAX_RETRY_NUM = 2;

    //团购券状态
    const COUPON_STATUS_USABLE = 0;//未使用
    const COUPON_STATUS_USED = 1;//已经使用
    const COUPON_STATUS_REFUNDINT_AUDITING = 2; //退款审核中
    const COUPON_STATUS_REFUNDINT_REJECT = 3;//退款拒绝
    const COUPON_STATUS_REFUNDINT_AUDITED = 4;//审核通过
    const COUPON_STATUS_REFUNDING = 5; //退款中
    const COUPON_STATUS_REFUNDED = 6; //退款成功
    const COUPON_STATUS_REFUND_FAIL = 7; //退款失败
    const COUPON_STATUS_EXPIRE = 8; // 过期

    //状态描述
    static $statusMap = array(
        self::COUPON_STATUS_USABLE => '未使用',
        self::COUPON_STATUS_USED => '已使用',
        self::COUPON_STATUS_REFUNDINT_AUDITING => '退款审核中',
        self::COUPON_STATUS_REFUNDINT_REJECT => '退款被拒绝',
        self::COUPON_STATUS_REFUNDINT_AUDITED => '审核通过',
        self::COUPON_STATUS_REFUNDING => '退款中',
        self::COUPON_STATUS_REFUNDED => '退款成功',
        self::COUPON_STATUS_REFUND_FAIL => '退款失败',
        self::COUPON_STATUS_EXPIRE => '已过期',
    );
    
    // 团购券类型
    const COUPON_TYPE_OWN = 1;
    const COUPON_TYPE_THIRD = 3;
    const COUPON_TYPE_TPV2 = 4;
    const COUPON_TYPE_DELIVERY = 5;

    // 团购券标志
    const COUPON_FLAG_SINGLE = 1;//单码
    const COUPON_FLAG_COMPLEX = 2;//复码
    const COUPON_FLAG_MULTI = 3;//一码多刷

    //团购券干预类型
    const COUPON_INTERPOSE_TYPE_NON = 0;//无干预
    const COUPON_INTERPOSE_TYPE_FREE = 1;//免单
    const COUPON_INTERPOSE_TYPE_RREEZE = 2;//冻结

    //团购券干预状态
    const COUPON_INTERPOSE_STATUS_PROCESS = 1;//处理中
    const COUPON_INTERPOSE_STATUS_OK = 2;//干预成功
    const COUPON_INTERPOSE_STATUS_ERR = 3;//干预失败

    //第三方团购券的分配状态
    const THIRD_COUPON_STATUS_NOALLOC = 0;
    const THIRD_COUPON_STATUS_ALLOCED = 1;
    const THIRD_COUPON_STATUS_DROP = 2;

    //短信发送方
    const COUPON_SMS_SENDER_SYSTEM = 0; //系统自动发送
    const COUPON_SMS_SENDER_USER = 1; //用户自己发送
    const COUPON_SMS_SENDER_MIS = 2; //百度客服发送
    const COUPON_SMS_SENDER_MOBILE = 3; //用户在无线端自行发送
    const COUPON_SMS_SENDER_TPV2 = 4; //TPV2的第三方客服发送

    //发送短信的场景
    const SMS_SCENARIO_BUY = 1;
    const SMS_SCENARIO_REFUND = 2;
    const SMS_SCENARIO_VERIFY = 3;
    const SMS_SCENARIO_EXPIRING_NOTIFICATION = 4;
    const SMS_SCENARIO_REFUND_SUCCESS = 5;
    const SMS_SCENARIO_REFUND_ERROR = 6;

    //将退款的状态映射到券自身的状态
    static $refundStatusMap = array(
        SF_Const_Refund::STATUS_PASS => SF_Const_Coupon::COUPON_STATUS_REFUNDINT_AUDITED,
        SF_Const_Refund::STATUS_FAIL => SF_Const_Coupon::COUPON_STATUS_REFUND_FAIL,
        SF_Const_Refund::STATUS_WAITING => SF_Const_Coupon::COUPON_STATUS_REFUNDINT_AUDITING,
        SF_Const_Refund::STATUS_REFUSE => SF_Const_Coupon::COUPON_STATUS_REFUNDINT_REJECT,
        SF_Const_Refund::STATUS_REFUNDING => SF_Const_Coupon::COUPON_STATUS_REFUNDING,
        SF_Const_Refund::STATUS_SUCC => SF_Const_Coupon::COUPON_STATUS_REFUNDED,
    );

    //退款的状态到干预状态的映射
    static $interPoseStatusMap = array(
        SF_Const_Refund::STATUS_SUCC => SF_Const_Coupon::COUPON_INTERPOSE_STATUS_OK,
        SF_Const_Refund::STATUS_FAIL => SF_Const_Coupon::COUPON_INTERPOSE_STATUS_ERR,
        SF_Const_Refund::STATUS_REFUNDING => SF_Const_Coupon::COUPON_INTERPOSE_STATUS_PROCESS,
        SF_Const_Refund::STATUS_WAITING => SF_Const_Coupon::COUPON_INTERPOSE_STATUS_PROCESS,
    );
}
