<?php
class SF_Const_Order {
    CONST TRADE_PARAMS_REQUEST_ID = 'requestId';
    CONST TRADE_PARAMS_TRADE_NO = 'ext';
    CONST TRADE_PARAMS_TRADE_FROM = 'tradeFrom';
    CONST TRADE_PARAMS_DEVICE_TYPE = 'deviceType';
    CONST TRADE_PARAMS_TX_NO = 'txNo';
    /**
     * 订单购买上限
     */
    CONST MAX_BUY_LIMIT = 1000;
    /**
     * 订单状态机:
     */
    CONST STATUS_UNPAY = 10;
    CONST SUBSTATUS_UNPAY_INIT = 11;
    CONST SUBSTATUS_UNPAY_CLOSE = 12;
    CONST SUBSTATUS_UNPAY_FAIL = 13;
    CONST SUBSTATUS_UNPAY_EXPIRE = 14;
    CONST STATUS_PAY = 20;
    CONST SUBSTATUS_PAY_INIT = 1;
    CONST SUBSTATUS_PAY_VERIFY = 2;
    CONST SUBSTATUS_PAY_REFUND = 4;
    CONST SUBSTATUS_PAY_EXPIRE = 8;
    CONST STATUS_REFUND = 30;
    CONST SUBSTATUS_REFUND_INIT = 31;
    CONST SUBSTATUS_REFUND_DONE = 32;
    CONST SUBSTATUS_REFUND_FAIL = 33;
    CONST STATUS_VERIFY = 40;
    CONST SUBSTATUS_VERIFY_INIT = 41;
    CONST STATUS_EXPIRE = 50;
    CONST SUBSTATUS_EXPIRE_INIT = 51;
    CONST STATUS_DELETE = 60;
    CONST SUBSTATUS_DELETE_INIT = 61;
    /**
     * 退款类型:
     */
    CONST REFUND_TYPE_PAY = 1;
    CONST REFUND_TYPE_AUTO = 2;
    CONST REFUND_TYPE_USER = 3;
    CONST REFUND_TYPE_MIS = 4;
    CONST REFUND_TYPE_TP = 5;
    CONST REFUND_COMPEL_CRM = 6;
    CONST REFUND_TYPE_TP_AUDIT_CALLBACK = 7;
    CONST REFUND_TYPE_ZHIFU = 8;
    /**
     * 订单是否可见: 0-不可见, 1-可见
     */
    CONST IS_INVISIBLE = 0;
    CONST IS_VISIBLE = 1;
    /**
     * 订单是否已发货:
     * 0-未发货，默认;
     * 1-已发货
     */
    CONST IS_NOT_DELIVERED = 0;
    CONST IS_DELIVERED = 1;
    /**
     * 订单系统保护（频率）命令号;
     */
    CONST COMMAND_NO_ACTSCTROL_ORDER_OPERATE = 50001;
    /**
     * 订单类型，继承自商品类型
     */
    CONST ORDER_TYPE_COM = 1;
    CONST ORDER_TYPE_LOTT = 2;
    CONST ORDER_TYPE_THIRD_COUPON = 3;
    CONST ORDER_TYPE_TPV2 = 4;
    CONST ORDER_TYPE_DELIVERY = 5;
    /**
     * 订单idalloc name
     */
    CONST KSARCH_IDALLOC_ORDERID = 'order_id';
    /**
     * 抽奖订单，是否中奖标志
     */
    CONST ORDER_LOTTERY_STATUS_NO = 0;
    CONST ORDER_LOTTERY_STATUS_YES = 1;
}
